services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=music_lib
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/music_lib
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
